[font.normal]
family = "MesloLGS NF"

[shell]
program = "/opt/homebrew/bin/tmux"

[font]
size = 18

[window]
option_as_alt = "Both"

# Map Mac CMD to Ctrl-Space (my tmux prefix)
[keyboard]
bindings = [
  # New Window Split Horizont
  { key = "Return", mods = "Command",  chars = "\u0000\\"},
  # new Window Split Vertical
  { key = "Return", mods = "Command|Shift",  chars = "\u0000|"},
  # For some reason alacritty sends thhrough S-CR as just CR
  # by default
  { key = "Return", mods = "Shift", chars = "\u001b[13;2u" },
  { key = "}", mods = "Command|Shift",  chars = "\u0000n"},
  { key = "}", mods = "Command|Shift",  chars = "\u0000n"},
  { key = "{", mods = "Command|Shift",  chars = "\u0000p"},
  { key = "|", mods = "Command|Shift",  chars = "\u0000|"},
  { key = "\\", mods = "Command",  chars = "\u0000\\"},
  { key = "I", mods = "Command",  chars = "\u0000x"},
  { key = "O", mods = "Command",  chars = "\u0000O"},
  { key = ";", mods = "Command",  chars = "\u0000:"},
  { key = "r", mods = "Command",  chars = "\u0000\u0012"},
  { key = "]", mods = "Command",  chars = "\u0000o"},
  { key = "[", mods = "Command",  chars = "\u0000;"},
  { key = "L", mods = "Command",  chars = "\u0000 "},
  { key = "L", mods = "Command|Shift",  chars = "\u0000z"},
  { key = "S", mods = "Command",  chars = "\u0000s"},
  { key = "D", mods = "Command",  chars = "\u0000w"},
  { key = "T", mods = "Command",  chars = "\u0000c"},
  # Detach pane into new tab
  { key = "T", mods = "Command|Shift",  chars = "\u0000!"},
  { key = "W", mods = "Command",  chars = "\u0000&"},
  # For this to work on mac you need to go to Keyboard Shortcuts
  # for Applications and override 'Hide alacritty' -> F12
  { key = "G", mods = "Command",  chars = "\u0000Q"},
  { key = "H", mods = "Command",  chars = "\u0000P"},
  { key = "J", mods = "Command",  chars = "\u0000["},
  { key = "P", mods = "Command",  chars = "\u0000]"},
  { key = "Z", mods = "Command",  chars = "\u0000z"},
  { key = "1", mods = "Command",  chars = "\u00000"},
  { key = "2", mods = "Command",  chars = "\u00001"},
  { key = "3", mods = "Command",  chars = "\u00002"},
  { key = "4", mods = "Command",  chars = "\u00003"},
  { key = "5", mods = "Command",  chars = "\u00004"},
  { key = "6", mods = "Command",  chars = "\u00005"},
  { key = "7", mods = "Command",  chars = "\u00006"},
  { key = "8", mods = "Command",  chars = "\u00007"},
  { key = "9", mods = "Command",  chars = "\u0000e"},
]
