[mgr]
show_hidden = true
linemode = "mtime"

[opener]
edit = [
	{ run = 'hx "$@"', block = true, for = "unix" },
	{ run = 'open -a neovide "$@"', block = false, for = "unix", desc = "neovide" },
	# TODO: One dir up from file?
	{ run = 'open -a Finder "$@"', block = false, for = "unix", desc = "finder" },
	{ run = 'nvim "$@"', block = true, for = "unix" },
	{ run = 'emacsclient -c -a "emacs -nw" "$@"', block = true, for = "unix" },
]

[open]
prepend_rules = [
	{ name = "*.md", use = "edit" },
]
append_rules = [
	{ name = "*", use = "edit" },
]
