# https://docs.helix-editor.com/keymap.html
# https://github.com/helix-editor/helix/blob/master/helix-term/src/commands.rs
theme = "ayu_evolve"

[editor]
bufferline = "multiple"
shell = ["zsh", "-c"]
# whitespace.render = "all"

[keys.normal]
# C-s = ":w" # Maps Ctrl-s to the typable command :w which is an alias for :write (save file)
# C-o = ":open ~/.config/helix/config.toml" # Maps Ctrl-o to opening of the helix config file
# a = "move_char_left" # Maps the 'a' key to the move_char_left command
# w = "move_line_up" # Maps the 'w' key move_line_up
# "C-S-esc" = "extend_line" # Maps Ctrl-Shift-Escape to extend_line
# g = { a = "code_action" } # Maps `ga` to show possible code actions

# Paste big selection
"C-p" = ["extend_to_line_bounds", "yank", "paste_after", "add_newline_above"]
# Move lines up and down
"C-j" = ["extend_to_line_bounds", "delete_selection", "paste_after"]
"C-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before"]
# Duplicate line
q.p = ["extend_to_line_bounds", "yank", "paste_after"]
# Quick shortcuts for line end and begin
q.d = ["extend_to_line_bounds", "delete_selection"]
q.k = "goto_line_end"
q.j = "extend_to_line_end"
q.h = "extend_to_line_start"
g.o = "goto_file_start"
0 = "goto_line_start"
# Yank to clipboard
Y = "yank_main_selection_to_clipboard"
" " = { q = ":q", Q = ":q!"}

[keys.insert]
"A-x" = "normal_mode"
j = { k = "normal_mode", i = "normal_mode"}

[keys.select]
q = "extend_to_line_end"
0 = "extend_to_line_start"
Y = "yank_main_selection_to_primary_clipboard"
