[[language]]
name = "glsl"
scope = "source.glsl"
file-types = ["glsl", "vert", "tesc", "tese", "geom", "frag", "comp" ]
comment-token = "//"
block-comment-tokens = { start = "/*", end = "*/" }
indent = { tab-width = 4, unit = "    " }
injection-regex = "glsl"
# language-servers = ["glsl-lsp", "glsl-analyzer"]
language-servers = ["glsl-lsp"]

[language-server.glsl-lsp]
command = "glslls"
args = ["--stdin"]
# args = ["--stdin", "-v", "-l", "/tmp/glslls.log"]

[language-server.glsl-analyzer]
command = "glsl_analyzer"
args = ["--stdio"]

# https://github.com/helix-editor/helix/issues/5479#issuecomment-1669522115
[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]
config = {} # buggy behaviour, you need a pyproject.toml and pyrightconfig.json

[[language]]
name = "python"
formatter = { command = "ruff", args = ["--quiet", "-"] }
auto-format = true
roots = ["pyproject.toml"]
language-servers = [ "pyright" ]
